"use client";

import { useState } from "react";
import { FileBarChart, Download, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/ui/page-header";
import { cn } from "@/lib/utils";

interface ReportMeta {
  id: string;
  name: string;
  description: string;
  badge: string;
  icon: string;
}

const REPORTS: ReportMeta[] = [
  {
    id: "executive_summary",
    name: "Executive Summary",
    description: "Asset counts, risk distribution, and open issues — formatted for leadership or board review",
    badge: "Markdown",
    icon: "ES",
  },
  {
    id: "risk_report",
    name: "Risk Assessment",
    description: "Every AI asset by risk level. Includes ownership status, days since last review, and connected services",
    badge: "Markdown",
    icon: "RA",
  },
  {
    id: "compliance_report",
    name: "Compliance Summary",
    description: "Control coverage across HIPAA, SOC 2, EU AI Act, and ISO 42001 — suitable for auditor review",
    badge: "Markdown",
    icon: "CS",
  },
  {
    id: "orphaned_assets",
    name: "Unowned Assets",
    description: "All AI systems with no active owner on record, sorted by risk level. Useful for remediation planning",
    badge: "Markdown",
    icon: "UA",
  },
  {
    id: "policy_violations",
    name: "Policy Violations",
    description: "All open violations across your active policies, with asset details and first detection date",
    badge: "Markdown",
    icon: "PV",
  },
];

function getStoredTimestamp(reportId: string): string | null {
  if (typeof window === "undefined") return null;
  return localStorage.getItem(`report_generated_${reportId}`);
}

function setStoredTimestamp(reportId: string) {
  if (typeof window === "undefined") return;
  localStorage.setItem(`report_generated_${reportId}`, new Date().toISOString());
}

function formatTimestamp(ts: string | null): string | null {
  if (!ts) return null;
  return new Date(ts).toLocaleString();
}

export default function ReportsPage() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [timestamps, setTimestamps] = useState<Record<string, string | null>>(() => {
    const ts: Record<string, string | null> = {};
    for (const r of REPORTS) {
      ts[r.id] = getStoredTimestamp(r.id);
    }
    return ts;
  });

  async function generateReport(reportId: string) {
    setGenerating(reportId);
    try {
      // Fetch all data needed for report
      const [analyticsRes, complianceRes, orgRes] = await Promise.all([
        fetch("/api/analytics").then(r => r.json()),
        fetch("/api/compliance").then(r => r.json()).catch(() => ({ data: null })),
        fetch("/api/org").then(r => r.json()),
      ]);

      const analytics = analyticsRes.data ?? {};
      const compliance = complianceRes.data ?? null;
      const org = orgRes.data ?? {};
      const generatedAt = new Date().toISOString();
      const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

      let content = "";
      let filename = "";

      switch (reportId) {
        case "executive_summary":
          filename = `spekris-executive-summary-${generatedAt.slice(0, 10)}.md`;
          content = [
            `# AI Asset Management — Executive Summary`,
            `**Organization:** ${org.name}  |  **Plan:** ${org.plan}  |  **Generated:** ${dateStr}`,
            ``,
            `## Overview`,
            `| Metric | Value |`,
            `|--------|-------|`,
            `| Total AI Assets | ${analytics.totalAssets ?? 0} |`,
            `| Critical Risk Assets | ${analytics.assetsByRiskLevel?.critical ?? 0} |`,
            `| High Risk Assets | ${analytics.assetsByRiskLevel?.high ?? 0} |`,
            `| Orphaned Assets | ${analytics.orphanedAssets ?? 0} |`,
            `| Open Policy Violations | ${analytics.openViolations ?? 0} |`,
            `| Active Connectors | ${analytics.connectorCount ?? 0} |`,
            ``,
            `## Risk Distribution`,
            ...Object.entries(analytics.assetsByRiskLevel ?? {}).map(([level, count]) =>
              `- **${level.toUpperCase()}:** ${count} assets`
            ),
            ``,
            `## Sources`,
            ...Object.entries(analytics.assetsBySource ?? {}).map(([source, count]) =>
              `- **${source}:** ${count} assets`
            ),
            ``,
            `## Recommended Actions`,
            analytics.orphanedAssets > 0 ? `- ACTION REQUIRED: **Assign owners** to ${analytics.orphanedAssets} orphaned asset(s) — these represent unmanaged AI risk` : ``,
            (analytics.assetsByRiskLevel?.critical ?? 0) > 0 ? `- URGENT: **Review** ${analytics.assetsByRiskLevel?.critical} critical-risk asset(s) immediately` : ``,
            analytics.openViolations > 0 ? `- ACTION REQUIRED: **Resolve** ${analytics.openViolations} open policy violation(s)` : ``,
            ``,
            `---`,
            `*Generated by Spekris AI Asset Management — spekris.ai*`,
          ].filter(l => l !== "").join("\n");
          break;

        case "risk_report":
          filename = `spekris-risk-report-${generatedAt.slice(0, 10)}.md`;
          content = [
            `# AI Risk Assessment Report`,
            `**Organization:** ${org.name}  |  **Generated:** ${dateStr}`,
            ``,
            `## Summary`,
            `Total assets: ${analytics.totalAssets ?? 0}`,
            ``,
            `## Risk Distribution`,
            `| Risk Level | Count | % of Total |`,
            `|------------|-------|------------|`,
            ...(["critical", "high", "medium", "low"] as const).map(level => {
              const count = analytics.assetsByRiskLevel?.[level] ?? 0;
              const pct = analytics.totalAssets > 0 ? Math.round(count / analytics.totalAssets * 100) : 0;
              return `| ${level.toUpperCase()} | ${count} | ${pct}% |`;
            }),
            ``,
            `## Ownership Status`,
            ...Object.entries(({} as Record<string,number>)).map(([status, count]) =>
              `- **${status.replace(/_/g, " ")}:** ${count}`
            ),
            ``,
            `## Open Policy Violations: ${analytics.openViolations ?? 0}`,
            `## Open Tasks: 0`,
            ``,
            `---`,
            `*Generated by Spekris AI Asset Management*`,
          ].join("\n");
          break;

        case "orphaned_assets":
          filename = `spekris-orphaned-assets-${generatedAt.slice(0, 10)}.md`;
          content = [
            `# Orphaned AI Assets Report`,
            `**Organization:** ${org.name}  |  **Generated:** ${dateStr}`,
            ``,
            `**Total orphaned assets: ${analytics.orphanedAssets ?? 0}**`,
            ``,
            `An orphaned asset has no active owner — either the original creator left the organization,`,
            `or ownership was never established. These represent the highest governance risk.`,
            ``,
            `## Remediation`,
            `1. Review each orphaned asset in the Asset Registry`,
            `2. Assign an active owner from your team`,
            `3. Document the asset's purpose and risk level`,
            `4. Set up a policy to auto-alert when assets become orphaned`,
            ``,
            `[View orphaned assets in Spekris →](/platform/assets?owner_status=orphaned)`,
            ``,
            `---`,
            `*Generated by Spekris AI Asset Management*`,
          ].join("\n");
          break;

        case "policy_violations":
          filename = `spekris-policy-violations-${generatedAt.slice(0, 10)}.md`;
          content = [
            `# Policy Violations Report`,
            `**Organization:** ${org.name}  |  **Generated:** ${dateStr}`,
            ``,
            `**Open violations: ${analytics.openViolations ?? 0}**`,
            `**Critical/High: ${analytics.criticalAssets ?? 0}**`,
            ``,
            `[View all violations in Spekris →](/platform/policies)`,
            ``,
            `---`,
            `*Generated by Spekris AI Asset Management*`,
          ].join("\n");
          break;

        default:
          filename = `spekris-${reportId}-${generatedAt.slice(0, 10)}.json`;
          content = JSON.stringify({
            generated_at: generatedAt, report_type: reportId, analytics, compliance,
          }, null, 2);
      }

      const mimeType = filename.endsWith(".md") ? "text/markdown" : "application/json";
      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);

      setStoredTimestamp(reportId);
      setTimestamps((prev) => ({ ...prev, [reportId]: new Date().toISOString() }));
    } finally {
      setGenerating(null);
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Generate and download compliance, risk, and ownership reports for auditors, leadership, and due diligence."
      />

      <div className="grid gap-4 sm:grid-cols-2">
        {REPORTS.map((report) => {
          const lastGenerated = formatTimestamp(timestamps[report.id] ?? null);
          return (
            <div
              key={report.id}
              className="nx-surface flex flex-col gap-4 p-5"
            >
              <div className="flex items-start gap-3">
                <div className="flex size-9 shrink-0 items-center justify-center rounded-md border border-border bg-muted/40 text-[11px] font-semibold text-muted-foreground">
                  {report.icon}
                </div>
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2">
                    <h3 className="text-[14px] font-semibold tracking-tight">
                      {report.name}
                    </h3>
                    <span className="inline-flex h-4 items-center rounded-sm border border-border bg-muted/40 px-1.5 text-[10px] text-muted-foreground">
                      {report.badge}
                    </span>
                  </div>
                  <p className="mt-1 text-[12px] leading-relaxed text-muted-foreground">
                    {report.description}
                  </p>
                  {lastGenerated && (
                    <p className="mt-2 text-[11px] text-muted-foreground/70">
                      Last generated: {lastGenerated}
                    </p>
                  )}
                </div>
              </div>
              <Button
                variant="outline"
                size="sm"
                className="w-full"
                onClick={() => generateReport(report.id)}
                disabled={generating === report.id}
              >
                {generating === report.id ? (
                  <>
                    <Loader2 className="size-3.5 animate-spin" />
                    Generating
                  </>
                ) : (
                  <>
                    <Download className="size-3.5" />
                    Generate report
                  </>
                )}
              </Button>
            </div>
          );
        })}
      </div>

      <div className="rounded-lg border border-primary/20 bg-primary/5 p-5">
        <div className="flex items-start gap-3">
          <FileBarChart className="mt-0.5 size-5 shrink-0 text-primary" />
          <div>
            <h3 className="text-[14px] font-semibold">
              M&amp;A Due Diligence Pack
            </h3>
            <p className="mt-1 max-w-xl text-[13px] leading-relaxed text-muted-foreground">
              Full AI asset inventory for acquisition due diligence. Includes
              complete inventory, risk assessment, ownership chain, compliance
              status, and executive summary. Used by PE firms and corporate
              development teams.
            </p>
            <div className="mt-3 flex items-center gap-3">
              <span className="inline-flex h-5 items-center rounded-sm bg-primary/10 px-1.5 text-[10px] font-semibold uppercase tracking-wide text-primary">
                Enterprise
              </span>
              <Button size="sm" variant="outline">
                Contact sales
              </Button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
