"use client";

import { useState } from "react";
import { FileBarChart, Download, Loader2 } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

interface ReportMeta {
  id: string;
  name: string;
  description: string;
  badge: string;
  icon: string;
}

const REPORTS: ReportMeta[] = [
  {
    id: "executive_summary",
    name: "Executive Summary",
    description: "Board-ready overview of your AI asset posture, risk distribution, and key metrics",
    badge: "PDF + JSON",
    icon: "📊",
  },
  {
    id: "risk_report",
    name: "Risk Assessment Report",
    description: "Detailed breakdown of all AI assets by risk level, with remediation recommendations",
    badge: "PDF",
    icon: "⚠️",
  },
  {
    id: "compliance_report",
    name: "Compliance Report",
    description: "Full compliance posture across all enabled frameworks",
    badge: "PDF",
    icon: "📋",
  },
  {
    id: "orphaned_assets",
    name: "Orphaned Assets Report",
    description: "All AI systems with no active owner, sorted by risk level",
    badge: "CSV + PDF",
    icon: "👻",
  },
  {
    id: "policy_violations",
    name: "Policy Violations Report",
    description: "All open policy violations across your organization",
    badge: "PDF",
    icon: "🚨",
  },
];

function getStoredTimestamp(reportId: string): string | null {
  if (typeof window === "undefined") return null;
  return localStorage.getItem(`report_generated_${reportId}`);
}

function setStoredTimestamp(reportId: string) {
  if (typeof window === "undefined") return;
  localStorage.setItem(`report_generated_${reportId}`, new Date().toISOString());
}

function formatTimestamp(ts: string | null): string | null {
  if (!ts) return null;
  return new Date(ts).toLocaleString();
}

export default function ReportsPage() {
  const [generating, setGenerating] = useState<string | null>(null);
  const [timestamps, setTimestamps] = useState<Record<string, string | null>>(() => {
    const ts: Record<string, string | null> = {};
    for (const r of REPORTS) {
      ts[r.id] = getStoredTimestamp(r.id);
    }
    return ts;
  });

  async function generateReport(reportId: string) {
    setGenerating(reportId);
    try {
      // Fetch all data needed for report
      const [analyticsRes, complianceRes, orgRes] = await Promise.all([
        fetch("/api/analytics").then(r => r.json()),
        fetch("/api/compliance").then(r => r.json()).catch(() => ({ data: null })),
        fetch("/api/org").then(r => r.json()),
      ]);

      const analytics = analyticsRes.data ?? {};
      const compliance = complianceRes.data ?? null;
      const org = orgRes.data ?? {};
      const generatedAt = new Date().toISOString();
      const dateStr = new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });

      let content = "";
      let filename = "";

      switch (reportId) {
        case "executive_summary":
          filename = `nexus-executive-summary-${generatedAt.slice(0, 10)}.md`;
          content = [
            `# AI Asset Management — Executive Summary`,
            `**Organization:** ${org.name}  |  **Plan:** ${org.plan}  |  **Generated:** ${dateStr}`,
            ``,
            `## Overview`,
            `| Metric | Value |`,
            `|--------|-------|`,
            `| Total AI Assets | ${analytics.totalAssets ?? 0} |`,
            `| Critical Risk Assets | ${analytics.assetsByRiskLevel?.critical ?? 0} |`,
            `| High Risk Assets | ${analytics.assetsByRiskLevel?.high ?? 0} |`,
            `| Orphaned Assets | ${analytics.orphanedAssets ?? 0} |`,
            `| Open Policy Violations | ${analytics.openViolations ?? 0} |`,
            `| Active Connectors | ${analytics.connectorCount ?? 0} |`,
            ``,
            `## Risk Distribution`,
            ...Object.entries(analytics.assetsByRiskLevel ?? {}).map(([level, count]) =>
              `- **${level.toUpperCase()}:** ${count} assets`
            ),
            ``,
            `## Sources`,
            ...Object.entries(analytics.assetsBySource ?? {}).map(([source, count]) =>
              `- **${source}:** ${count} assets`
            ),
            ``,
            `## Recommended Actions`,
            analytics.orphanedAssets > 0 ? `- ⚠️ **Assign owners** to ${analytics.orphanedAssets} orphaned asset(s) — these represent unmanaged AI risk` : ``,
            (analytics.assetsByRiskLevel?.critical ?? 0) > 0 ? `- 🔴 **Review** ${analytics.assetsByRiskLevel?.critical} critical-risk asset(s) immediately` : ``,
            analytics.openViolations > 0 ? `- 🚨 **Resolve** ${analytics.openViolations} open policy violation(s)` : ``,
            ``,
            `---`,
            `*Generated by Nexus AI Asset Management — nexus.ai*`,
          ].filter(l => l !== "").join("\n");
          break;

        case "risk_report":
          filename = `nexus-risk-report-${generatedAt.slice(0, 10)}.md`;
          content = [
            `# AI Risk Assessment Report`,
            `**Organization:** ${org.name}  |  **Generated:** ${dateStr}`,
            ``,
            `## Summary`,
            `Total assets: ${analytics.totalAssets ?? 0}`,
            ``,
            `## Risk Distribution`,
            `| Risk Level | Count | % of Total |`,
            `|------------|-------|------------|`,
            ...(["critical", "high", "medium", "low"] as const).map(level => {
              const count = analytics.assetsByRiskLevel?.[level] ?? 0;
              const pct = analytics.totalAssets > 0 ? Math.round(count / analytics.totalAssets * 100) : 0;
              return `| ${level.toUpperCase()} | ${count} | ${pct}% |`;
            }),
            ``,
            `## Ownership Status`,
            ...Object.entries(({} as Record<string,number>)).map(([status, count]) =>
              `- **${status.replace(/_/g, " ")}:** ${count}`
            ),
            ``,
            `## Open Policy Violations: ${analytics.openViolations ?? 0}`,
            `## Open Tasks: 0`,
            ``,
            `---`,
            `*Generated by Nexus AI Asset Management*`,
          ].join("\n");
          break;

        case "orphaned_assets":
          filename = `nexus-orphaned-assets-${generatedAt.slice(0, 10)}.md`;
          content = [
            `# Orphaned AI Assets Report`,
            `**Organization:** ${org.name}  |  **Generated:** ${dateStr}`,
            ``,
            `**Total orphaned assets: ${analytics.orphanedAssets ?? 0}**`,
            ``,
            `An orphaned asset has no active owner — either the original creator left the organization,`,
            `or ownership was never established. These represent the highest governance risk.`,
            ``,
            `## Remediation`,
            `1. Review each orphaned asset in the Asset Registry`,
            `2. Assign an active owner from your team`,
            `3. Document the asset's purpose and risk level`,
            `4. Set up a policy to auto-alert when assets become orphaned`,
            ``,
            `[View orphaned assets in Nexus →](/platform/assets?owner_status=orphaned)`,
            ``,
            `---`,
            `*Generated by Nexus AI Asset Management*`,
          ].join("\n");
          break;

        case "policy_violations":
          filename = `nexus-policy-violations-${generatedAt.slice(0, 10)}.md`;
          content = [
            `# Policy Violations Report`,
            `**Organization:** ${org.name}  |  **Generated:** ${dateStr}`,
            ``,
            `**Open violations: ${analytics.openViolations ?? 0}**`,
            `**Critical/High: ${analytics.criticalAssets ?? 0}**`,
            ``,
            `[View all violations in Nexus →](/platform/policies)`,
            ``,
            `---`,
            `*Generated by Nexus AI Asset Management*`,
          ].join("\n");
          break;

        default:
          filename = `nexus-${reportId}-${generatedAt.slice(0, 10)}.json`;
          content = JSON.stringify({
            generated_at: generatedAt, report_type: reportId, analytics, compliance,
          }, null, 2);
      }

      const mimeType = filename.endsWith(".md") ? "text/markdown" : "application/json";
      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      a.click();
      URL.revokeObjectURL(url);

      setStoredTimestamp(reportId);
      setTimestamps((prev) => ({ ...prev, [reportId]: new Date().toISOString() }));
    } finally {
      setGenerating(null);
    }
  }

  return (
    <div className="p-6 lg:p-8 space-y-6 max-w-5xl mx-auto">
      <div>
        <h1 className="text-2xl font-bold">Reports</h1>
        <p className="text-muted-foreground mt-1">
          Generate and download compliance and risk reports
        </p>
      </div>

      <div className="grid sm:grid-cols-2 gap-4">
        {REPORTS.map((report) => {
          const lastGenerated = formatTimestamp(timestamps[report.id] ?? null);

          return (
            <Card key={report.id}>
              <CardContent className="pt-5">
                <div className="flex items-start gap-3 mb-4">
                  <span className="text-2xl">{report.icon}</span>
                  <div className="flex-1">
                    <div className="flex items-center gap-2">
                      <h3 className="font-semibold">{report.name}</h3>
                      <Badge variant="outline" className="text-xs">
                        {report.badge}
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground mt-1">{report.description}</p>
                    {lastGenerated && (
                      <p className="text-xs text-muted-foreground mt-2">
                        Last generated: {lastGenerated}
                      </p>
                    )}
                  </div>
                </div>
                <Button
                  size="sm"
                  variant="outline"
                  className="w-full"
                  onClick={() => generateReport(report.id)}
                  disabled={generating === report.id}
                >
                  {generating === report.id ? (
                    <>
                      <Loader2 className="h-3.5 w-3.5 mr-1.5 animate-spin" />
                      Generating...
                    </>
                  ) : (
                    <>
                      <Download className="h-3.5 w-3.5 mr-1.5" />
                      Generate Report
                    </>
                  )}
                </Button>
              </CardContent>
            </Card>
          );
        })}
      </div>

      <Card className="border-primary/20 bg-primary/5">
        <CardContent className="pt-5">
          <div className="flex items-start gap-3">
            <FileBarChart className="h-5 w-5 text-primary mt-0.5" />
            <div>
              <h3 className="font-semibold">M&A Due Diligence Pack</h3>
              <p className="text-sm text-muted-foreground mt-1">
                Full AI asset inventory for acquisition due diligence. Includes complete
                inventory, risk assessment, ownership chain, compliance status, and executive
                summary. Used by PE firms and corporate development teams.
              </p>
              <div className="flex items-center gap-3 mt-3">
                <Badge>Enterprise Feature</Badge>
                <Button size="sm" variant="outline">
                  Contact Sales
                </Button>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
